### ISSUE TITLE
Provisioned dashboard does not work

### ISSUE THREAD

**Issue by johntdyer** [Clarity-89/grafana-finnhub#2]
I am trying to get the provisioned dashboard to see the datasource, it doesnt seem to like the template somehow

![image](https://user-images.githubusercontent.com/58234/92955471-2cc77500-f433-11ea-91a7-edbefdba9f57.png)

My plugin name is "Finnhub" just like in the dashboard.json so I am not sure what else it wants

**Comment by Clarity-89** [comment]
Hi, thanks for the issue and sorry for the late reply. Hmm, not sure what could be wrong here, seems like an issue on Grafana side.

**Comment by Clarity-89** [comment]
Actually this might have been an issue with the plugin itself. @johntdyer does https://github.com/Clarity-89/grafana-finnhub/pull/5 fix it for you?
