### ISSUE TITLE
Variable is not interpolated

### ISSUE THREAD

**Issue by yolkhovyy** [Clarity-89/grafana-finnhub#3]
Please see attached screenshot.

![Screenshot from 2020-09-26 00-01-07 2](https://user-images.githubusercontent.com/9390324/94320092-65676280-ff8c-11ea-8f96-77536d4e67e0.png)

**Comment by Clarity-89** [comment]
Hi, thanks for the issue and sorry for the late reply. There's no variable interpolation support for this plugin yet.
