### ISSUE TITLE
[Feature request] Add support for Grafana variables in Finnhub plugin queries

### ISSUE THREAD

**Issue by dc-thanh** [Clarity-89/grafana-finnhub#52]
Hi @Clarity-89,  I am currently using the Finnhub plugin in Grafana and have encountered a limitation related to the use of Grafana variables in panel queries. It seems that the plugin does not support variables like $symbol, which makes it difficult to create dynamic dashboards where stock symbols can be selected/changed.

**Comment by Clarity-89** [comment]
Should be fixed by https://github.com/Clarity-89/grafana-finnhub/pull/53, but only for the `$symbol` use case.
